[package]
name = "compile-commands-post"
version = "0.1.0"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]
license = "Apache-2.0/MIT"
readme = "README.md"

[dependencies]
error-chain = "~0.11"
serde = "~1"
serde_derive = "~1"
serde_json = "~1"
regex = "~0.2"
